twitch:
  debug: false  # Enables debug logging
  send_to_discord: false  # Sends Twitch messages to a Discord webhook
  token: "oauth:your_token_here"  # OAuth token for Twitch bot

  message_format: "[TWITCH] %nickname%: %message%"  # Format for Twitch messages in Minecraft chat
  prefix: "[TWITCH]"  # Prefix used in plugin messages

  discord:
    use_heads: true  # Use player avatars from mc-heads.net
    webhook_url: "https://discord.com/api/webhooks/your_webhook_id/your_webhook_token"  # Discord webhook URL
    custom_avatar_url: "https://example.com/avatar.png"  # Custom avatar URL if use_heads is false

  channels:
    - "channel1:streamer_nickname"  # Channel with linked Minecraft player
    - "channel2"  # Channel without linked player

  blacklist:
    users:
      - "bot_nickname1"
      - "bot_nickname2"
    prefixes:
      - "!"
      - "#"
    words:
      - "inappropriate_word1"
      - "inappropriate_word2"

sql:
  enabled: false  # Enables MySQL connection
  host: "localhost"
  port: 3306
  database: "twitch"
  username: "user"
  password: "pass"
