name: Twitch
author: MEGATREX4
main: org.megatrex4.twitch.Twitch
version: 1.5
api-version: 1.21
website: https://megatrex4.netlify.app/
description: Twitch chat plugin

commands:
  twitchlink:
    description: Link your Twitch account
    usage: /twitchlink <add|remove|reload> <channel>
    permission: twitch.link

permissions:
  twitch.add:
    description: Allows adding Twitch channels
    default: op
  twitch.remove:
    description: Allows removing Twitch channels
    default: op
  twitch.reload:
    description: Allows reloading the plugin
    default: op
