name: Twitch
author: MEGATREX4
main: org.megatrex4.twitch.Twitch
version: 1.7
api-version: 1.21
website: https://megatrex4.netlify.app/
description: Twitch chat plugin

commands:
  twitchlink:
    description: Twitch control command
    usage: /twitchlink <add|remove|reload|blacklist>
    permission: twitch.link

permissions:
  twitch.add:
    description: Allows adding Twitch channels
    default: op
  twitch.remove:
    description: Allows removing Twitch channels
    default: op
  twitch.reload:
    description: Allows reloading the plugin
    default: op
  twitch.blacklist:
    description: Allows modifying blacklist (add/remove word/prefix/user)
    default: op

